version: '3.9'
services:
  eureka-server:
    container_name: eureka-server
    build:
      context: docker-eureka-server
      dockerfile: Dockerfile
    image: eureka-server:latest
    ports:
      - 8761:8761
    networks:
      - spring-cloud-network
  product-server:
    container_name: product-server
    build:
      context: docker-product-server
      dockerfile: Dockerfile
    image: product-server:latest
    ports:
      - 19999:9999
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge



# https://www.baeldung.com/dockerizing-spring-boot-application

# docker-compose config
# docker-compose up --build
# docker-compose down

# multiple port
# ports:
#    - 18800-18888:8888

# docker-compose --file docker-compose-scale.yml up -d --build --scale message-server=1 product-server=1
# docker-compose --file docker-compose-scale.yml up -d --build --scale message-server=3 product-server=2